/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package bot.clawd.hello;

public final class R {
  public static final class anim {
    public static final int fade_slide_up=0x7f010000;
  }
  public static final class color {
    public static final int cloudy_end=0x7f020000;
    public static final int cloudy_start=0x7f020001;
    public static final int default_end=0x7f020002;
    public static final int default_start=0x7f020003;
    public static final int glass_border=0x7f020004;
    public static final int glass_white=0x7f020005;
    public static final int rainy_end=0x7f020006;
    public static final int rainy_start=0x7f020007;
    public static final int sunny_end=0x7f020008;
    public static final int sunny_start=0x7f020009;
  }
  public static final class drawable {
    public static final int card_bg=0x7f030000;
    public static final int main_bg=0x7f030001;
    public static final int weather_bg=0x7f030002;
  }
  public static final class id {
    public static final int aqi_advice=0x7f040000;
    public static final int aqi_badge=0x7f040001;
    public static final int aqi_card=0x7f040002;
    public static final int aqi_value=0x7f040003;
    public static final int condition_emoji=0x7f040004;
    public static final int condition_text=0x7f040005;
    public static final int feels_like_text=0x7f040006;
    public static final int forecast_container=0x7f040007;
    public static final int gps_btn=0x7f040008;
    public static final int hourly_container=0x7f040009;
    public static final int humidity_text=0x7f04000a;
    public static final int insight_text=0x7f04000b;
    public static final int loader_overlay=0x7f04000c;
    public static final int loader_text=0x7f04000d;
    public static final int location_text=0x7f04000e;
    public static final int moon_emoji=0x7f04000f;
    public static final int moon_illumination=0x7f040010;
    public static final int moon_phase_text=0x7f040011;
    public static final int no2_value=0x7f040012;
    public static final int outfit_card=0x7f040013;
    public static final int outfit_text=0x7f040014;
    public static final int pm10_value=0x7f040015;
    public static final int pm25_value=0x7f040016;
    public static final int refresh_btn=0x7f040017;
    public static final int root_layout=0x7f040018;
    public static final int save_city_btn=0x7f040019;
    public static final int saved_cities_container=0x7f04001a;
    public static final int saved_scroll=0x7f04001b;
    public static final int search_btn=0x7f04001c;
    public static final int search_input=0x7f04001d;
    public static final int share_btn=0x7f04001e;
    public static final int sunrise_compact=0x7f04001f;
    public static final int temp_text=0x7f040020;
    public static final int weather_content=0x7f040021;
    public static final int wind_text=0x7f040022;
  }
  public static final class layout {
    public static final int activity_main=0x7f050000;
  }
  public static final class string {
    public static final int app_name=0x7f060000;
  }
}